### ISSUE TITLE
Meta tags doubled in production

### ISSUE THREAD

**Issue by lorisleiva** [lorisleiva/vuepress-plugin-seo#1]
In development:

<img width="469" alt="screenshot 2019-02-02 at 11 22 03" src="https://user-images.githubusercontent.com/3642397/52163657-fd8c4600-26dc-11e9-91f0-845d97e5ae47.png">

In production:

<img width="559" alt="screenshot 2019-02-02 at 11 21 42" src="https://user-images.githubusercontent.com/3642397/52163660-0250fa00-26dd-11e9-8ea7-a3d1a3706cef.png">

In production, the bottom batch of meta tags are updated when we switch pages but the top batch stays static and matches the page that we originally loaded.

Not sure if this is a SSR issue related to Vuepress or if this is just related to my project but I need to fix that.

Any insights on this issue would be much appreciated 🙂

**Comment by adamdehaven** [comment]
It's likely because you defined meta data in the $page.frontmatter as well as using this plugin.

**Comment by lorisleiva** [comment]
That was not the case. It was an issue with Vuepress itself which seems to have been fixed on the 2nd of February 2020. I'll close that for now but reopen if I found out that the bug still exists.
