### ISSUE TITLE
[Feature Request] Rel canonical tags

### ISSUE THREAD

**Issue by logicmason** [lorisleiva/vuepress-plugin-seo#2]
One common SEO concern for anyone syndicating their content is that their own site gets the credited for their articles (instead of Medium, Dev.to, etc)

The common pattern on those sites is to take this from the front matter. I.e., `canonical_url: https://example.com/my-article` in the front matter will result in the following being in the head of the published article:
`<link rel="canonical" href="https://example.com/my-article/" />`

**Comment by lorisleiva** [comment]
Hi there 👋 

Thanks for raising this.

I'll try to implement something as soon as I've got some free time otherwise I wouldn't be opposed to a PR.

**Comment by logicmason** [comment]
Great! Sorry about not writing one. I would if I were more familiar with
VuePress (and may yet at some point!)

Loris Leiva <notifications@github.com> 於 2019年12月18日 週三 上午1:00 寫道：

**Comment by adarshmadrecha** [comment]
Any plan to add `canonical` links meta tag? 
`<link rel="canonical" href="https://example.com/my-article/" />`

**Comment by adarshmadrecha** [comment]
Vuepress `v1.7.0` added support for canonical links.

Just add below on top of any markdown file.
```md
---
canonical: https://google.com
---
```

Reference: https://github.com/vuejs/vuepress/pull/2658
