### ISSUE TITLE
Mismatched label - data pair

### ISSUE THREAD

**Issue by matuskosut** [lorisleiva/vuepress-plugin-seo#5]
Should it be twitter:data1 when twitter:label1 is used to reference author? Otherwise it seems to overlap with tags

https://github.com/lorisleiva/vuepress-plugin-seo/blob/de13ee10a826a60101fbc00ac2e09493881ce2c0/index.js#L80

**Comment by lorisleiva** [comment]
Hi there 👋 

Well spotted, thanks! Would you mind creating a small PR for me?

🙇
